version: "3"
services:
  hub:
    image: selenium/hub:3.14     
  chrome:
    image: selenium/node-chrome:3.14    
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
  firefox:
    image: selenium/node-firefox:3.141
    shm_size: '1gb'
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
  book-flight-module1:
    image: rajasha/selenium-docker
    depends_on:
      - chrome
      - firefox
    environment:
      - BROWSER=firefox
      - HUB_HOST=hub
      - MODULE=book-flight-module.xml    
  book-flight-module2:
    image: rajasha/selenium-docker
    depends_on:
      - chrome
      - firefox
    environment:
      - BROWSER=chrome
      - HUB_HOST=hub
      - MODULE=book-flight-module.xml  
    volumes:
      - C:/Users/DockerHost/dockercompose1/workspace/SELENIUM_DOCKER_RUNNER/test-output:/Users/Selenium/test-output
  search-module1:
    image: rajasha/selenium-docker
    depends_on:
      - chrome
      - firefox
    environment:
      - BROWSER=chrome
      - HUB_HOST=hub
      - MODULE=search-module.xml
  search-module2:
    image: rajasha/selenium-docker
    depends_on:
      - chrome
      - firefox
    environment:
      - BROWSER=firefox
      - HUB_HOST=hub
      - MODULE=search-module.xml